<div style="text-align: center; margin: auto; clear: both;">

        <div class="block-title">
            <strong>
                <a href="/retail-store"><?php echo $this->getStoreName(); ?></a>
            </strong>
        </div>
        <p>
            <a href="/retail-store">
                <?php echo $this->getAddress(); ?> <br/>
                <?php echo $this->getTodaysHours(); ?>
            </a>
        </p>
</div>
