<?php
/**
 * @var $this  Zf_StoreInfo_Block_Hours
 */
?>
<h1><?php echo $this->getStoreName() ?></h1>
<h3>Business Hours</h3>
<table class="business-hours">
    <tr><th class="text-right">Monday:    </th><td> <?php echo $this->getWeekdayHours('monday'); ?></td><tr>
    <tr><th class="text-right">Tuesday:   </th><td> <?php echo $this->getWeekdayHours('tuesday'); ?></td><tr>
    <tr><th class="text-right">Wednesday: </th><td> <?php echo $this->getWeekdayHours('wednesday'); ?></td><tr>
    <tr><th class="text-right">Thursday:  </th><td> <?php echo $this->getWeekdayHours('thursday'); ?></td><tr>
    <tr><th class="text-right">Friday:    </th><td> <?php echo $this->getWeekdayHours('friday'); ?></td><tr>
    <tr><th class="text-right">Saturday:  </th><td> <?php echo $this->getWeekdayHours('saturday'); ?></td><tr>
    <tr><th class="text-right">Sunday:    </th><td> <?php echo $this->getWeekdayHours('sunday'); ?></td><tr>
</table>
<br>

<?php $exceptions = $this->getCurrentExceptions(); ?>

<?php if($exceptions): ?>
    <h4>Upcoming Special Hours</h4>
    <ul class="business-hours-exceptions">
        <?php foreach ($exceptions as $exception): ?>
        <li>
            <b><?php echo $this->formatDateString($exception['date'], 'D n/j') ?></b>
            <b> &nbsp; <?php echo $exception['hours'] ?></b>
            <span> &nbsp;&nbsp; <?php echo $exception['note'] ?></span>
        </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<br><br>

<h3>Location</h3>
<ul>
    <li><b>Address: </b> <?php echo $this->getAddress() ?></li>
    <li><b>Phone Number: </b> <?php echo $this->getPhoneNumber() ?></li>
</ul>

<br><br>

<iframe src="<?php echo $this->getGoogleMapsUrl() ?>"
        width="600" height="450" frameborder="0" style="border:0; max-width: 100%;" allowfullscreen></iframe>
